### ISSUE TITLE
Any help for collect resources

### ISSUE THREAD

**Issue by Ivory94** [AXeL-dev/Dindo-Bot#10]
Hello,

I started using DIndo-Bot for collecting resources on only one map.
I have selected resources, save, create a path for collecting, however there is only on click to select the resource but none to perform the action.

Any ideas on how can we do it ?

Regards,

**Comment by AXeL-dev** [comment]
Can you attach your `path` &`maps.data` files here please

**Comment by Ivory94** [comment]
Oh okay, thanks for the video.
Collection action is not the same on retro, I think, that s why cannot work :(

**Comment by AXeL-dev** [comment]
> Oh okay, thanks for the video.
> Collection action is not the same on retro, I think, that s why cannot work :(

What changes on Retro for collect action? any details would be helpful

**Comment by Ivory94** [comment]
You have to click on the resource, then click on the action

**Comment by AXeL-dev** [comment]
Okay, i get it, i'll add 2 options in the bot settings:
- 1st one to enable clicking on the action after clicking on  the resource (will be optional to stay compatible with newer dofus versions).
- 2nd option: Collect time varies in Retro i guess so i'll add an option to set a custom collect time.

P.S: I have one more question, can we use keyboard shortcut to click on action (after clicking on the resource), if yes, which one please (i don't have dofus Retro installed on my PC right now..). Thanks.

**Comment by Ivory94** [comment]
nice, thanks a lot.

Keep us updated,

Regards.

**Comment by Ivory94** [comment]
Did not find any shortcut which can be enabled.
Please find an example  below.
[https://ibb.co/sJKNd1R](url)

**Comment by AXeL-dev** [comment]
@Ivory94 can you try now & check if the collect action work?

**Note**: Don't forget to change game version option in settings before testing.

**Comment by Ivory94** [comment]
Hello,
Now I ve got a click on the resource, but there is no click on the action.
https://ibb.co/6WDNZnq
Regards

**Comment by AXeL-dev** [comment]
> Now I ve got a click on the resource, but there is no click on the action.

Have you change the game version in bot settings to **Retro** ?

Also could you send me your `logs/*.log` & `settings.json` files?

**Comment by Ivory94** [comment]
Sorry I was not at home for a week.
It is working well.

Thanks
