### ISSUE TITLE
Not recognizing

### ISSUE THREAD

**Issue by greyzerr** [AXeL-dev/Dindo-Bot#14]
Let's start of by thanking you for your work! it works amazing!.
I only ran in the issue that it does not work for me with iron and nettles. Is this a known issue or is there something I can do to fix this?

My python skills are not that great yet but maybe in the future I can help develop some things.

**Comment by greyzerr** [comment]
Got it working. It just need to be very precise.

**Comment by AXeL-dev** [comment]
Yeah, i confirm that sometimes you need to be very precise to get the wanted results, this is somehow a lack in pixels bot, but what can we do for that! maybe in the future i'll look at implementing an AI for pixel matching/recognition, but till then the only solution is to be very precise ![image](https://user-images.githubusercontent.com/30635693/73605897-849c2480-45a4-11ea-97c0-dc7b476ffb33.png)
