### ISSUE TITLE
Bot freezes up and does not collect resources

### ISSUE THREAD

**Issue by awc782** [AXeL-dev/Dindo-Bot#16]
Moving from map to map works fine for me when running the bot, but when it gets to the collect action it freezes up.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/jae/Desktop/Dindo-Bot/threads/bot.py", line 42, in run
    self.interpret(instructions)
  File "/home/jae/Desktop/Dindo-Bot/threads/bot.py", line 102, in interpret
    self.collect(instruction['map'], instruction['store_path'])
  File "/home/jae/Desktop/Dindo-Bot/threads/job.py", line 39, in collect
    screen = tools.screen_game(self.game_location)
  File "/home/jae/Desktop/Dindo-Bot/lib/tools.py", line 96, in screen_game
    raw = root.get_image(x, y, width, height, X.ZPixmap, 0xffffffff)
  File "/usr/lib/python2.7/dist-packages/Xlib/xobject/drawable.py", line 266, in get_image
    plane_mask = plane_mask)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
BadMatch: <class 'Xlib.error.BadMatch'>: code = 8, resource_id = 294, sequence_number = 13, major_opcode = 73, minor_opcode = 0
```

This is the error that shows up in terminal, I also have tried disabling Check resources color. 
Thanks for replying! This is a really cool project you are working on.

**Comment by AXeL-dev** [comment]
I think this is due to python version, please retry using python3:
```
python3 bot.py
```

**Comment by awc782** [comment]
This is what shows up when running with python3. I also installed python3-xlib.

```
jae@x220:~/Desktop/Dindo-Bot$ python3 bot.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jae/Desktop/Dindo-Bot/threads/bot.py", line 42, in run
    self.interpret(instructions)
  File "/home/jae/Desktop/Dindo-Bot/threads/bot.py", line 102, in interpret
    self.collect(instruction['map'], instruction['store_path'])
  File "/home/jae/Desktop/Dindo-Bot/threads/job.py", line 39, in collect
    screen = tools.screen_game(self.game_location)
  File "/home/jae/Desktop/Dindo-Bot/lib/tools.py", line 96, in screen_game
    raw = root.get_image(x, y, width, height, X.ZPixmap, 0xffffffff)
  File "/usr/lib/python3/dist-packages/Xlib/xobject/drawable.py", line 266, in get_image
    plane_mask = plane_mask)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3/dist-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadMatch: <class 'Xlib.error.BadMatch'>: code = 8, resource_id = 294, sequence_number = 13, major_opcode = 73, minor_opcode = 0
```

**Comment by AXeL-dev** [comment]
Okay, i need to investigate about this (once i get some free time).

By the way, what's your linux distrubution ? ubuntu? could you try on an another/updated linux distro?

**Comment by andrewchangshs** [comment]
My linux distribution is ubuntu bionic, I updated it to the most recent distro which is 18.04 but I am still receiving the same error. Thanks for the support!

**Comment by AXeL-dev** [comment]
Hey again, can you share your `maps.data` file here please? (it should be inside the Dindo-bot directory)

**Comment by awc782** [comment]
Hi, here is my maps.data and log files. I will try the fix and let you know if it works.

[maps.zip](https://github.com/AXeL-dev/Dindo-Bot/files/4471287/maps.zip)
[logs.zip](https://github.com/AXeL-dev/Dindo-Bot/files/4471299/logs.zip)

**Comment by awc782** [comment]
It works now! thank you for the support.

Just an additional question. If the bot goes to a map and sees an exhausted resource will it go on to the next resource or will it end? Is there any way of implementing functionality so that the bot waits until the resource pops up and continues with the map?

**Comment by AXeL-dev** [comment]
> It works now! thank you for the support.

Cool! x)

> Just an additional question. If the bot goes to a map and sees an exhausted resource will it go on to the next resource or will it end?

The actual behavior of the bot is to check the resource color before clicking on it, so if the color is wrong it will go to the next one (also, you can disable the color check from settings, but i do not recommend it). So the answer is no, the bot will not end before the path end, & what you can do to avoid this is to simply create a looped path & under the bot config, set a high number in repeat path option (in a way that the bot will always restart the path after its end/last action).

> Is there any way of implementing functionality so that the bot waits until the resource pops up and continues with the map?

This might be a good idea, but i think that moving to other maps is quite better then staying on the same map. Also, you can easily do that right now using the `Wait` action just after the `Collect` action, for example: if a resource needs 30 seconds to appear again, you just need to wait 30/40 sec after the collect action & loop/repeat the path many times (using the repeat option i told you about above).

I hope that's enough clear, 'cause i'm strugling to find the right words in english (i'm not too much used to it :confused: ).

**Comment by awc782** [comment]
It's really clear, I appreciate the effort. (Your english is perfect)

**Comment by awc782** [comment]
After testing the bot with enabled **color check** it seems that the bot does not recognize the resource pixel color. Throwing the error **Ignoring non-matching resource**

I will be attaching my log and map files if you need them.

[maps.zip](https://github.com/AXeL-dev/Dindo-Bot/files/4472146/maps.zip)
[logs.zip](https://github.com/AXeL-dev/Dindo-Bot/files/4472148/logs.zip)

**Comment by AXeL-dev** [comment]
This is kind of weird, did you move or resize the bot just after creating the map? also, what's your screen resolution?

**Comment by awc782** [comment]
I do not move or resize the bot after creating the map. Once the bot resizes and auto-snaps the window I don't touch it. My screen resolution is 1366x768.

**Comment by AXeL-dev** [comment]
Okay, i think i have an idea about why this is happening, could you please calculate the game window decoration height (represented by the square in the image below)?
![image](https://user-images.githubusercontent.com/30635693/79392329-252a9f80-7f6b-11ea-8ab1-b5f645656083.png)

& then try to reduce the window decoration value in the bot settings depending on the value you've calculate. You may need to recreate/refresh the map coordinates also before testing.

**Comment by andrewchangshs** [comment]
It took me a while to find the game window decoration height but it finally worked! I changed my window decoration value in the bot settings to 51 and that solved the problem.

**Comment by AXeL-dev** [comment]
I have completely removed that setting in the latest version of the bot & replaced it with automatic detection of the window decoration height. so, i may ask you to do another test with the [latest version](/AXeL-dev/Dindo-Bot/archive/master.zip) of the bot if you'ld like to.

**Comment by andrewchangshs** [comment]
I am testing the latest version of the bot and it seems to work. Will continue to test it out and let you know how it goes

**Comment by andrewchangshs** [comment]
One Issue that is coming up is that when the **Profession Level increased** popup shows up on the side, the bot simulates pressing the **esc** key but that brings up the main menu instead of closing the popup. 

Other than that when a character challenges you the bot will freeze, this may be a similar fix to closing the popup

**Comment by AXeL-dev** [comment]
I tried to fix the level up popup issue, but i didn't test it yet. In case it doesn't work you can still disable the feature from bot preferences. I've also restored the window decoration height option & made it optional.

**Comment by andrewchangshs** [comment]
Not sure if the changes caused this but sometimes the bot resizes the game window differently using window decoration height option, this causes everything to be shifted and the bot doesn't work.

**Comment by andrewchangshs** [comment]
The pod bar also updates to the wrong percentage.

**Comment by AXeL-dev** [comment]
I think that the resizing part needs to be reviewed. I'm facing the same issues somehow. I'll try to check that once i get some time to.

**Comment by AXeL-dev** [comment]
I'll close this issue and open a new one (since the main issue is already fixed).
