### ISSUE TITLE
screen always None

### ISSUE THREAD

**Issue by weslly99** [AXeL-dev/Dindo-Bot#17]
screen = Wnck.Screen.get_default() # returning always NoneType

Wnck-WARNING **: 09:51:38.037: libwnck is designed to work in X11 only, no valid display found

Debian Buster

**Comment by AXeL-dev** [comment]
This might be related to the wayland display server (check this https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894323), so what i can recommend you is to downgrade to an [LTS release of debian](https://wiki.debian.org/LTS) like Debian Stretch, or to try on an other Linux distro

**Comment by weslly99** [comment]
working perfectly on ubuntu 18.04, thanks
