### ISSUE TITLE
Using bot for Dofus touch ?

### ISSUE THREAD

**Issue by Gambl3r08** [AXeL-dev/Dindo-Bot#2]
Hi, How it could be modified for Dofus touch ?

**Comment by AXeL-dev** [comment]
If you are running Dofus touch on linux then you only need to modify the bot thread(s) to fit dofus touch gameplay (@see [threads folder](https://github.com/AXeL-dev/Dindo-Bot/tree/master/threads)), but in windows or mac case this may be more complicated because the bot is not yet compatible with them.

P.S.: I just noticed that the desktop version of the game is now using [wine](https://www.winehq.org/) on linux, & after some tests the game window embedding (inside the bot) is not working anymore.. (i guess it should still work for Dofus touch).

Finally, porting the bot to windows may be a solution (idk..).

**Comment by Gambl3r08** [comment]
yes am using Linux, but when i try running bot.py:
`python bot.py
Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    from gui.main import BotWindow
  File "/home/gambl3r/Descargas/Dindo-Bot-master/gui/main.py", line 8, in <module>
    from threads.bot import BotThread
  File "/home/gambl3r/Descargas/Dindo-Bot-master/threads/bot.py", line 108
    self.await()
             ^
SyntaxError: invalid syntax

`

**Comment by Gambl3r08** [comment]
`[gambl3r@gambl3r Dindo-Bot-master]$ python --version
Python 3.7.0
[gambl3r@gambl3r Dindo-Bot-master]$ python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    from gui.main import BotWindow
  File "/home/gambl3r/Descargas/Dindo-Bot-master/gui/main.py", line 8, in <module>
    from threads.bot import BotThread
  File "/home/gambl3r/Descargas/Dindo-Bot-master/threads/bot.py", line 108
    self.await()
             ^
SyntaxError: invalid syntax
`

**Comment by Gambl3r08** [comment]
i running in Manjaro and install python-xlib python-pil

**Comment by AXeL-dev** [comment]
i see, the problem could be the python version or maybe a missing python module on Manjaro ('cause it's working just fine on ubuntu 18.04), so i'm investigating but it could take time (i need to download the Manjaro iso first to test by myself).

Anyway, i will let you know if i got some news.

**Comment by Gambl3r08** [comment]
thanks, i will wait

**Comment by AXeL-dev** [comment]
It should be fixed now x)

**Comment by Gambl3r08** [comment]
it working, look the lindo no emu project [https://github.com/prixe/lindo](url)
I am new in the Python dev, but I want to learn to create Dofus touch bot in python like practice.
I do not know where to start

**Comment by AXeL-dev** [comment]
I heard about lindo, but i'm not sure about how it works exactly, whatever, i guess Dindo bot is a good start/base for you, you may also check [pyautogui](https://github.com/asweigart/pyautogui) module (Dindo-bot uses a custom version of it) & [pygtk](https://python-gtk-3-tutorial.readthedocs.io/en/latest/introduction.html#simple-example) to know how the gui works.

**Comment by Gambl3r08** [comment]
thanks, I started reading the documentation of pygtk and pyautogui, I'm understanding how it works
