### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by ak6o** [AXeL-dev/Dindo-Bot#22]
Hello,

I can see on the screenshot from the README a MacOS interface what are the part of the code that have to be changed to have support on MacOS when I tried sudo ./install.sh of course apt isnt available on mac so I modified the script using Homebrew. But there is still error the install.sh doesnt work...

How did you manage to make it work on MacOS (screenshot read me)

**Comment by AXeL-dev** [comment]
Hey,

I'm using [McMojave](https://www.gnome-look.org/p/1275087/) theme on my Linux distro, this is why the interface looks pretty much like a MAC.

So i never tried it on MAC & i do not have one at home to test, however, for the changes that needs to be made you can check issue #13 which is a duplicate of this one by the way, so please consider moving to the old issue & closing this one.
