### ISSUE TITLE
Can't find Game Window 

### ISSUE THREAD

**Issue by maxmax4369** [AXeL-dev/Dindo-Bot#24]
Hello Axel, 
I wanted to try your bot but I can't seem to ding my game window. How do you configure it ?

**Comment by AXeL-dev** [comment]
Hey,

I just tested on the latest version of dofus & it seems to work (i get the game window), so have you try to refresh the game window checkbox? or to launch the dofus game window before launching the bot?

Also, what's your OS? Linux? if so which version/distro? same for dofus version, are you using Retro or 2.x?
