### ISSUE TITLE
HOW TO INSTALL

### ISSUE THREAD

**Issue by gooeedo** [AXeL-dev/Dindo-Bot#26]
I'm sorry to bother you, but I'm having trouble executing the command 

chmod +x install.sh

This is the error:

Package python-gi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-gi' has no installation candidate
E: Unable to locate package python-xlib
E: Unable to locate package python-pil

could you help me fix it?
thanks for your availability and for your great work

**Comment by AXeL-dev** [comment]
Hello,

I guess that i need more informations to help you, like you distro name & version.

**Comment by gooeedo** [comment]
Hi,  i am using a linux virtual machine, here is the information you asked
me for, thank you for the help.

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 21.04
Release: 21.04
Codename: hirsute

$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="
https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute



Il giorno mar 31 ago 2021 alle ore 20:30 AXeL ***@***.***> ha
scritto:

**Comment by AXeL-dev** [comment]
Thanks for the details,

Well it seems that latest ubuntu version doesn't include/support some old python 2 packages, so for now i updated the install script to use python 3 packages by default (b5d06a5).

Let me know if that works for you.

**Comment by gooeedo** [comment]
Thank you for the fix, it works.
Now it doesn't give me errors, but when i run the bot with the command:

dindo-bot

i have this error

libwnck is designed to work in X11 only, no valid display found
Traceback (most recent call last):
  File "/usr/local/bin/dindo-bot", line 11, in <module>
    bot = BotWindow()
  File "/home/guido/Downloads/Dindo-Bot-master/gui/main.py", line 32, in
__init__
    self.create_tabs()
  File "/home/guido/Downloads/Dindo-Bot-master/gui/main.py", line 250, in
create_tabs
    self.populate_game_window_combo()
  File "/home/guido/Downloads/Dindo-Bot-master/gui/main.py", line 1024, in
populate_game_window_combo
    self.game_windowList = tools.get_game_window_list()
  File "/home/guido/Downloads/Dindo-Bot-master/lib/tools.py", line 27, in
get_game_window_list
    screen.force_update() # recommended per Wnck documentation
AttributeError: 'NoneType' object has no attribute 'force_update'

I tried to use the fix you suggested in a previous issue: sudo pacman -S
libwnck3, but i have sudo: pacman: command not found (sudo apt install
pacman doesn't work).
I also tried to do sudo apt-get install -y libwnck-3-0 but it doesn't work.


Il giorno mer 1 set 2021 alle ore 11:21 AXeL ***@***.***> ha
scritto:

**Comment by AXeL-dev** [comment]
The bot crash should be fixed, but you won't be able to get the list of active game windows.

Also the error you're getting is related to the wayland display server #17. What i can suggest is to use another flavor of ubuntu like [Ubuntu Budgie 21.04](https://ubuntubudgie.org/) (which does not relay on wayland i guess), or to downgrade to an LTS version like 18.04 or 20.04.

**Comment by gooeedo** [comment]
Thanks you so much for the help,  really appreciate everything you’ve
done,  couldn’t
have done it without you


Il giorno mer 1 set 2021 alle ore 20:55 AXeL ***@***.***> ha
scritto:

**Comment by AXeL-dev** [comment]
You're welcome, can you confirm which solution worked for you? (i'm kinda curious haha)

**Comment by gooeedo** [comment]
Used  Ubuntu Budgie 21.04 <https://ubuntubudgie.org/> on my virtual machine

Il giorno gio 2 set 2021 alle ore 11:32 AXeL ***@***.***> ha
scritto:

**Comment by AXeL-dev** [comment]
Alright! thanks for the confirmation, & don't hesitate to open new issues if you find any.

**Comment by gooeedo** [comment]
Sorry to bother you again, do you have any tips on how to play dofus on
linux? I installed the game, but when I press play on the ankama launcher
nothing happens. I tried with playonlinux, is it the right way?

Il giorno gio 2 set 2021 alle ore 11:49 AXeL ***@***.***> ha
scritto:
