### ISSUE TITLE
Game Window

### ISSUE THREAD

**Issue by Gambl3r08** [AXeL-dev/Dindo-Bot#3]
How to use the "Game window" option?, because you do not select

**Comment by AXeL-dev** [comment]
The Game window combobox will currently show only "Dofus" game windows if there is some active or visible ones, so for Dofus touch you need to get the window instance name "using your system monitor for example" & change the code here
https://github.com/AXeL-dev/Dindo-Bot/blob/1bea80bbf1128f3f95d63cf18721c3a8f580c0da/lib/tools.py#L29

**Comment by Gambl3r08** [comment]
i try witch the Dofus 2 but in Manjaro don't work, later try with Debian in VM

**Comment by AXeL-dev** [comment]
hum, i guess the name should be "Dofus Touch" of something like that, so to be sure you need to launch the game & then disable this comment below to get all active windows name (before launching the bot)
https://github.com/AXeL-dev/Dindo-Bot/blob/1bea80bbf1128f3f95d63cf18721c3a8f580c0da/lib/tools.py#L28

once you know the dofus touch window/instance name (from bot output in terminal), you should modify this line 
https://github.com/AXeL-dev/Dindo-Bot/blob/1bea80bbf1128f3f95d63cf18721c3a8f580c0da/lib/tools.py#L29

then launch the bot & see if you get something in the Game Window area.

P.S.: i don't think that trying on Debian will change something.

**Comment by Gambl3r08** [comment]
Thats works in Manjaro, thanks, i testing move in the map, feedback later
