### ISSUE TITLE
Dindo-Bot: game window embedding not working anymore

### ISSUE THREAD

**Issue by canerbasat** [AXeL-dev/Dindo-Bot#5]
Still Works?

**Comment by AXeL-dev** [comment]
Dofus Linux version is now using [wine](https://www.winehq.org/) so game window embedding stopped working..

A simple solution would be to remove embedding & simply put the bot window beside the game window (after resizing it), well, i'm not sure if this would be the best solution.

**Comment by p2635** [comment]
Is it possible to run the bot in wine itself?

**Comment by AXeL-dev** [comment]
this would be more complicated, the bot is not compatible with windows, so it may not work properly on wine..
I'm wondering why Dofus Linux version moved to wine after version 2.47.. the only reason i can think about is to keep adobe air updated to the latest version(s) (to know: adobe air updates on linux was suspended) or maybe to stop bots using window embedding like this one.. who knows..

**Comment by AXeL-dev** [comment]
you can select the game window (if dofus is opened) but once selected, it will not be embedded inside the bot, also the game window might be closed automatically (it was working fine on GTK windows before Dofus switched to wine). Then, the bot uses [Gtk](https://en.wikipedia.org/wiki/GTK%2B) for user interface & more exactly pygtk (python implementation for Gtk). 
By the way, wich linux version/distro are you using?

**Comment by p2635** [comment]
I'm using Kubuntu 18.04 (with messed up repos, I think I have unstable so I am basically 18.10), thanks for your help..

**Comment by AXeL-dev** [comment]
hum, weird that the desktop file didn't work on kubuntu 18.04.. anyway, if you want to improve the bot by yourself you should start by learning python, [OOP](https://en.wikipedia.org/wiki/Object-oriented_programming) & pygtk :)

P.S.: i stopped dofus from some months ago, but if ever i come back i'll surely update the bot (i guess).

**Comment by p2635** [comment]
Does it still work on the distro that you're on? (what distro is it?)

**Comment by AXeL-dev** [comment]
if you are talking about the desktop file then yes, i'm using ubuntu budgie 18.04 (i didn't try on 18.10)

**Comment by p2635** [comment]
It's not detecting the windows :( can you help me if you have time? tell me if you use discord or some other contact
