### ISSUE TITLE
Xlib.protocol.request.QueryExtension

### ISSUE THREAD

**Issue by lborruto** [AXeL-dev/Dindo-Bot#6]
Distro: devuan jessie (debian jessie based)
When: when opening the bot with `python bot.py`
Error: 
`Xlib.protocol.request.QueryExtension
Traceback (most recent call last):
  File "bot.py", line 11, in <module>
    bot = BotWindow()
  File "/home/bot/Desktop/Dindo-Bot/gui/main.py", line 30, in __init__
    self.create_header_bar(title)
  File "/home/bot/Desktop/Dindo-Bot/gui/main.py", line 162, in create_header_bar
    preferences_button = Gtk.ModelButton(' Preferences')
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'ModelButton'
`

Thanks.

**Comment by AXeL-dev** [comment]
Seems to be a gtk error & i guess it's related to old python version or a missing package, could you try using `python3 bot.py`

**Comment by lborruto** [comment]
> Seems to be a gtk error & i guess it's related to old python version or a missing package, could you try using `python3 bot.py`

Thanks for the quick answers!
Unfortunately: 
`Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    from gui.main import BotWindow
  File "/home/bot/Desktop/Dindo-Bot/gui/main.py", line 7, in <module>
    from lib import tools, logger, data, parser, settings, accounts, maps
  File "/home/bot/Desktop/Dindo-Bot/lib/tools.py", line 11, in <module>
    from Xlib import display, X
ImportError: No module named 'Xlib'
`

**Comment by AXeL-dev** [comment]
You need to install Xlib for python3 try with `sudo apt install python3-xlib` then run the bot again with python3

**Comment by lborruto** [comment]
> python3-xlib

Installed, and same error:

`  File "bot.py", line 11, in <module>
    bot = BotWindow()
  File "/home/bot/Desktop/Dindo-Bot/gui/main.py", line 30, in __init__
    self.create_header_bar(title)
  File "/home/bot/Desktop/Dindo-Bot/gui/main.py", line 162, in create_header_bar
    preferences_button = Gtk.ModelButton(' Preferences')
  File "/usr/lib/python3/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'ModelButton'
`

**Comment by AXeL-dev** [comment]
Okay i get it, the gtk package in debian jessie is outdated [v3.14](https://packages.debian.org/source/jessie/gtk+3.0) & the `'ModelButton'` class used in the bot GUI need version 3.16 of GTK, so the package need to be upgraded, here is the link for the debian stretch package [gtk+3.0 (3.22.11-1)](https://packages.debian.org/source/stretch/gtk+3.0), so just [download it](http://ftp.us.debian.org/debian/pool/main/g/gtk+3.0/gir1.2-gtk-3.0_3.22.11-1_amd64.deb) & try installing it using `sudo apt install gir1.2-gtk-3.0_3.22.11-1_amd64.deb` (you may need to do a `cd name_of_download_folder` before that)

P.S.: Are you a linux expert? if so i'll try to avoid giving you so much details :sweat_smile:

**Comment by lborruto** [comment]
> Okay i get it, the gtk package in debian jessie is outdated [v3.14](https://packages.debian.org/source/jessie/gtk+3.0) & the `'ModelButton'` [class](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/ModelButton.html) used in the bot GUI need version 3.16 of GTK, so the package need to be upgraded, here is the link for the debian stretch package [gtk+3.0 (3.22.11-1)](https://packages.debian.org/source/stretch/gtk+3.0), so just [download it](http://ftp.us.debian.org/debian/pool/main/g/gtk+3.0/gir1.2-gtk-3.0_3.22.11-1_amd64.deb) & try installing it using `sudo apt install gir1.2-gtk-3.0_3.22.11-1_amd64.deb` (you may need to do a `cd name_of_download_folder` before that)
> 
> P.S.: Are you a linux expert? if so i'll try to avoid giving you so much details 😅

Thanks I understand what you said :)
But It cause me dependency issues:

`dpkg: error processing archive gir1.2-gtk-3.0_3.22.11-1_amd64.deb (--install):
 installing gir1.2-gtk-3.0:amd64 would break python-gi, and
 deconfiguration is not permitted (--auto-deconfigure might help)
Errors were encountered while processing:
 gir1.2-gtk-3.0_3.22.11-1_amd64.deb
`
I'll try to figure this out...

**Comment by AXeL-dev** [comment]
I thought it will (give you dependencies issues), so you could try doing a full upgrade of all the packages & distro using
```
sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
```
Keep in mind that the full upgrade may break things in your distro (welcome to the linux world where things break suddenly XD), so as a suggestion, maybe try it on a virtual machine first & if things goes right then you can go ahead (otherwise, just try using an updated linux distro & the bot should work without issues)

**Comment by lborruto** [comment]
> I thought it will (give you dependencies issues), so you could try doing a full upgrade of all the packages & distro using
> 
> ```
> sudo apt update
> sudo apt upgrade
> sudo apt dist-upgrade
> ```
> 
> Keep in mind that the full upgrade may break things in your distro (welcome to the linux world where things break suddenly XD), so as a suggestion, maybe try it on a virtual machine first & if things goes right then you can go ahead (otherwise, just try using an updated linux distro & the bot should work without issues)

It's not working either.. What distro could you recommend for running Dofus + the bot on 1gb ram? I'm using Devuan because of the 512mb ram requirement

**Comment by lborruto** [comment]
Confirmed it worked with Lubuntu 18.04!

**Comment by AXeL-dev** [comment]
Great, i also recommend you Xubuntu for a lightweight distro
